### ISSUE TITLE
Artifacts are missing from Helm bundle

### ISSUE THREAD

**Issue by ivett-da** [digital-asset/decentralized-canton-sync#25]
The dars are not consistent between release bundles. For example, if I compare 0.1.16 (0.1.16_cn-node-0.1.0-SNAPSHOT.tar.gz) and 0.1.17 (0.1.17_cn-node-0.1.0-SNAPSHOT.tar.gz) versions then I see that in 0.1.17 there are dars that are missing (it was there in 0.1.16 version)
Note that according to the [release notes](https://network.canton.global/release_notes.html ) there were no dar/artifact changes, so I expect the same dars in both bundles.

This is what I see in 0.1.16:
![image](https://github.com/user-attachments/assets/c754aca9-ecca-4400-9629-6a48b0238d9a)

and this is in 0.1.17:
![image](https://github.com/user-attachments/assets/08f2e347-2615-4f13-8f2f-1a3bf3ef63ca)

Missing dars in 0.1.17 are:
- splice-amulet-0.1.4.dar
- splice-wallet-0.1.4.dar
- splice-wallet-payments-0.1.4.dar
- splice-util-0.1.1.dar

**Comment by moritzkiefer-da** [comment]
Hi, this all seems to be fixed in 0.1.18 so I'm closing this. I think there was a brief period where the release bundle for 0.1.17 was actually the one for 0.1.15 which you may have stumbled upon.

If you still see issues with 0.1.18 or newer please open a new issue.
